from scoring import score_farmer
from preprocessing import preprocess_for_scoring
import pandas as pd

# Single farmer
y_sample = {
    "Unnamed: 0": 2,
    "hh_size": 4,
    "hh_dependency_ratio": 0.25,
    "age_manager": 31,
    "hh_primary_education": 1,
    "hh_formal_education": 3,
    "farm_size": 5.8,
    "farm_work": 2,
    "livestock": 12,
    "inorganic_fertilizer": 1,
    "fertilizer_per_ha": 110.2,
    "yield_kg_ha": 3400.5,
    "yield_stability": 0.88,
    "rainfall_mm": 1100.0,
    "soil_quality_index": 81.9,
    "soil_npk": "20-10-10",
    "drought_risk": 0.1,
    "climate_stress_index": 0.15,
    "crop_health_index": 0.91,
    "tx_frequency": 24,
    "total_volume": 1850.0,
    "avg_transaction": 77.08,
    "input_purchase_ratio": 0.85,
    "cashflow_volatility": 0.12,
    "fraud_rate": 0.0,
    "input_efficiency": 0.89,
    "hh_shock": 0,
    "drought_shock": 0,
    "dist_market": 5.2,
    "country": "Zambia",
    "main_crop_clean_MAIZE": 0,
    "main_crop_clean_MILLET": 0,
    "main_crop_clean_NUTS": 0,
    "main_crop_clean_OTHER": 0,
    "main_crop_clean_RICE": 0,
    "main_crop_clean_SORGHUM": 0,
    "main_crop_clean_TUBERS_ROOT": 0,
    "main_crop_clean_WHEAT": 1
  }

my_sample = [
  {
    "Unnamed: 0": 0,
    "hh_size": 5,
    "hh_dependency_ratio": 0.4,
    "age_manager": 42,
    "hh_primary_education": 1,
    "hh_formal_education": 2,
    "farm_size": 2.5,
    "farm_work": 3,
    "livestock": 4,
    "inorganic_fertilizer": 1,
    "fertilizer_per_ha": 60.5,
    "yield_kg_ha": 2100.0,
    "yield_stability": 0.75,
    "rainfall_mm": 850.2,
    "soil_quality_index": 68.4,
    "soil_npk": "15-15-15",
    "drought_risk": 0.2,
    "climate_stress_index": 0.35,
    "crop_health_index": 0.82,
    "tx_frequency": 12,
    "total_volume": 450.0,
    "avg_transaction": 37.5,
    "input_purchase_ratio": 0.65,
    "cashflow_volatility": 0.18,
    "fraud_rate": 0.0,
    "input_efficiency": 0.72,
    "hh_shock": 0,
    "drought_shock": 0,
    "dist_market": 12.4,
    "country": "Kenya",
    "main_crop_clean_MAIZE": 1,
    "main_crop_clean_MILLET": 0,
    "main_crop_clean_NUTS": 0,
    "main_crop_clean_OTHER": 0,
    "main_crop_clean_RICE": 0,
    "main_crop_clean_SORGHUM": 0,
    "main_crop_clean_TUBERS_ROOT": 0,
    "main_crop_clean_WHEAT": 0
  },
  {
    "Unnamed: 0": 1,
    "hh_size": 8,
    "hh_dependency_ratio": 0.6,
    "age_manager": 55,
    "hh_primary_education": 1,
    "hh_formal_education": 1,
    "farm_size": 1.2,
    "farm_work": 5,
    "livestock": 1,
    "inorganic_fertilizer": 0,
    "fertilizer_per_ha": 0.0,
    "yield_kg_ha": 950.0,
    "yield_stability": 0.45,
    "rainfall_mm": 420.5,
    "soil_quality_index": 42.1,
    "soil_npk": "0-0-0",
    "drought_risk": 0.8,
    "climate_stress_index": 0.78,
    "crop_health_index": 0.45,
    "tx_frequency": 4,
    "total_volume": 120.0,
    "avg_transaction": 30.0,
    "input_purchase_ratio": 0.20,
    "cashflow_volatility": 0.45,
    "fraud_rate": 0.01,
    "input_efficiency": 0.35,
    "hh_shock": 1,
    "drought_shock": 1,
    "dist_market": 28.1,
    "country": "Tanzania",
    "main_crop_clean_MAIZE": 0,
    "main_crop_clean_MILLET": 0,
    "main_crop_clean_NUTS": 0,
    "main_crop_clean_OTHER": 0,
    "main_crop_clean_RICE": 0,
    "main_crop_clean_SORGHUM": 1,
    "main_crop_clean_TUBERS_ROOT": 0,
    "main_crop_clean_WHEAT": 0
  },
  {
    "Unnamed: 0": 2,
    "hh_size": 4,
    "hh_dependency_ratio": 0.25,
    "age_manager": 31,
    "hh_primary_education": 1,
    "hh_formal_education": 3,
    "farm_size": 5.8,
    "farm_work": 2,
    "livestock": 12,
    "inorganic_fertilizer": 1,
    "fertilizer_per_ha": 110.2,
    "yield_kg_ha": 3400.5,
    "yield_stability": 0.88,
    "rainfall_mm": 1100.0,
    "soil_quality_index": 81.9,
    "soil_npk": "20-10-10",
    "drought_risk": 0.1,
    "climate_stress_index": 0.15,
    "crop_health_index": 0.91,
    "tx_frequency": 24,
    "total_volume": 1850.0,
    "avg_transaction": 77.08,
    "input_purchase_ratio": 0.85,
    "cashflow_volatility": 0.12,
    "fraud_rate": 0.0,
    "input_efficiency": 0.89,
    "hh_shock": 0,
    "drought_shock": 0,
    "dist_market": 5.2,
    "country": "Zambia",
    "main_crop_clean_MAIZE": 0,
    "main_crop_clean_MILLET": 0,
    "main_crop_clean_NUTS": 0,
    "main_crop_clean_OTHER": 0,
    "main_crop_clean_RICE": 0,
    "main_crop_clean_SORGHUM": 0,
    "main_crop_clean_TUBERS_ROOT": 0,
    "main_crop_clean_WHEAT": 1
  }
]


sample =  my_sample
df_sample = pd.DataFrame([sample])
X = preprocess_for_scoring(df_sample)
print("Final dtypes check:")
print(X.dtypes.value_counts())
print("Shape:", X.shape)



result = score_farmer(my_sample)
print(result)